### ISSUE TITLE
Migrate repo to use new release workflow

### ISSUE THREAD

**Issue by tedim52** [kurtosis-tech/example-datastore-server#17]
This repo contains outdated scripts:

- `update-package-versions.sh`
- `update-own-version-const.sh`
- `release.sh`

These scripts should be updated to use Kurtosis new release process through and tools through a PR such as the one made for [kurtosis-core`](https://github.com/kurtosis-tech/kurtosis-core/pull/632)

**Comment by mieubrisse** [comment]
Closing in favor of #20
